### PR TITLE
#1388 Should not show recommendations for others

### LINKED ISSUE #1388: Should not show recommendations for others
**Describe the bug**
As an admin, it is possible to view other users' documents when opening documents on the annotation page. This should be read-only. However, when recommenders are enabled, it is possible to see and accept recommendations in others' documents thereby changing these documents.

**To Reproduce**
1. Configure recommenders for your project
2. Get some suggestions for a user
3. Log in as an admin user
4. Open a document of the other user
5. See and accept recommendations even though you should not be allowed to.

**Please complete the following information:**
 - Version and build ID: 0.11.2
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by UWinch**
**What's in the PR**
If a user is viewing others' documents (as admin or for curation):
- disable recommendation sidebar forms
- do not show predictions
- do not trigger training

Closes #1388, #1377

**How to test manually**
For #1388 
* Configure recommenders for your project
* Get some suggestions for a user
* Log in as an admin user
* Open a document of the other user
* Make sure that no recommendations are shown and the recommendation sidebar is disabled

For #1377 
* Switch to curation page after annotating with recommendations
* Make sure that no recommendations are shown on the curation page

### CODE REVIEW

**Comment by reckart** [comment]
@jcklie could you have a look at this PR please?

File: inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java [hunk 1]
```diff
@@ -245,6 +250,12 @@ private void actionRejectRecommendation(AnnotationActionHandler aActionHandler,
     public void render(CAS aCas, AnnotatorState aState, VDocument aVDoc,
                        int aWindowBeginOffset, int aWindowEndOffset)
     {
+        // do not show predictions during curation or when viewing others' work
+        if (aState.getMode().equals(Mode.CURATION) ||
```
Comment (jcklie) [inline inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java]: Rather than checking for not curation (blacklisting), I would check here whether it is annotation (whitelisting), so that the error does not appear in the next mode we add

File: inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.java [hunk 2]
```diff
@@ -102,14 +107,29 @@ public RecommendationSidebar(String aId, IModel<AnnotatorState> aModel,
...
     }
 
     @Override
     protected void onConfigure()
     {
         // using onConfigure as last state in lifecycle to configure visibility
         super.onConfigure();
+        configureMismatched();
+        AnnotatorState state = getModelObject();
+        if (state.getMode().equals(Mode.CURATION)
```
Comment (jcklie) [inline inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.java]: You could do 
`boolean enabled = state.getMode().equals(Mode.CURATION) || !state.getUser().equals(userRepository.getCurrentUser()))`
and then do

	     form.setEnabled(enabled);
        recommenderInfos.setEnabled(enabled);

Then it is not so convoluted to me. It would also be nice to have a comment here why we need that.

Comment (reckart) [reply inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.java]: Since the sidebar is only shown on the annotation page and not on the curation page, do we need to check the Mode at all?

Comment (UWinch) [reply inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.java]: thx, good ideas, done
